# Generated by Django 3.2.4 on 2022-07-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='nombre mascota')),
                ('edad', models.IntegerField(max_length=70, verbose_name='edad mascota')),
                ('raza', models.CharField(max_length=70, verbose_name='raza mascota')),
                ('descripcion', models.TextField()),
                ('nacimiento', models.DateField()),
            ],
        ),
    ]
